<a href="https://colab.research.google.com/github/aga5711/data-science-kurs/blob/main/kurs_pandas_cs1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [ ]:
A = np.array([[2,4], [-1,3]])
np.trace(A)

5

In [ ]:
np.eye(7, dtype = 'int')

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [ ]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
np.set_printoptions(precision=4, suppress=True)

In [ ]:
np.dot(B,A)


array([[ 1., -0.],
       [ 0.,  1.]])

In [ ]:
A = np.array([[2,4], [1, -1]])
B = np.array([[10], [-1]])
A
B

array([[10],
       [-1]])

In [ ]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [ ]:
x,y = np.dot(A_inv, B)
print(x)
print(y)

[1.]
[2.]


In [3]:
df1 = pd.DataFrame(data=[12,12,32], index=['first','second','third'], columns=['col_1'])
df2 = pd.DataFrame(data=[12,12,32])
print(df1)
print(df2)

        col_1
first      12
second     12
third      32
    0
0  12
1  12
2  32


In [5]:
df3= pd.DataFrame(data=[[12,12,32],[15,16,17]], index=['first','second'], columns=['col_1', 'col_2', 'col_3'])
print(df3)

        col_1  col_2  col_3
first      12     12     32
second     15     16     17


In [7]:
df3['col_1']

first     12
second    15
Name: col_1, dtype: int64