<a href="https://colab.research.google.com/github/aga5711/data-science-kurs/blob/main/kurs_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2,4], [-1,3]])
np.trace(A)

5

In [ ]:
np.eye(7, dtype = 'int')

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [ ]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [ ]:
np.set_printoptions(precision=4, suppress=True)

In [ ]:
np.dot(B,A)


array([[ 1., -0.],
       [ 0.,  1.]])

In [ ]:
A = np.array([[2,4], [1, -1]])
B = np.array([[10], [-1]])
A
B

array([[10],
       [-1]])

In [ ]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [ ]:
x,y = np.dot(A_inv, B)
print(x)
print(y)

[1.]
[2.]
