<a href="https://colab.research.google.com/github/aga5711/data-science-kurs/blob/main/kurs_testy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A = np.random.seed(0)

In [ ]:
np.random.randn(10)

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [ ]:
A = np.random.rand(5)
A

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [ ]:
np.argmax(A)

3

In [ ]:
A[np.argmax(A)]

0.925596638292661

In [ ]:
np.argsort(A)

array([4, 1, 2, 0, 3])